### ISSUE TITLE
使用插件会导致chrome的手机模拟渲染样式出错

### ISSUE THREAD

**Issue by xiewl** [kinglisky/aidou#7]
<img width="1091" alt="qq20180305-150028 2x" src="https://user-images.githubusercontent.com/15881722/36961419-32531b42-2086-11e8-94aa-639f89d265b9.png">
<img width="1134" alt="qq20180305-150104 2x" src="https://user-images.githubusercontent.com/15881722/36961418-321d7dde-2086-11e8-8500-3cb7b8e4876a.png">

淘宝手机站也有相似问题，基本上可以看出是基于viewport的响应布局都会出现渲染问题
<img width="492" alt="qq20180305-145341 2x" src="https://user-images.githubusercontent.com/15881722/36961466-7a985b2e-2086-11e8-9ff9-c01350b07a8b.png">

**Comment by kinglisky** [comment]
@xiewl 插件会往页面插入一个 `iframe`, 估计是影响了页面的结构导致的，这个已经在优化了，准备将  `iframe` 内容移到 `popup`  页中，减少对内容页面的影响。

**Comment by kinglisky** [comment]
@xiewl 已经改了一版将内容移动到 popup 页中，应该不会再这种情况了。
![](https://i.loli.net/2018/03/07/5aa00772399db.jpg)

**Comment by xiewl** [comment]
![image](https://i.loli.net/2018/03/09/5aa231b9b74d5.jpg)
